# Stages
stages:
  - test
  - publish

# Global variables
variables:
  APIKEY: $APIKEY

# Jobs
test:
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: test
  allow_failure: false
  script:
    - dotnet build && dotnet test

publish:
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: publish
  only:
    - master
  allow_failure: false
  script:
    - dotnet build && dotnet pack
    - find Core -type f -name '*.nupkg' | xargs -I {} sh -c "dotnet nuget push {} --api-key $APIKEY --source https://api.nuget.org/v3/index.json --skip-duplicate"